### ISSUE TITLE
GPUassert: invalid device function ../nv_wavenet_util.cuh 48

### ISSUE THREAD

**Issue by PetrochukM** [NVIDIA/nv-wavenet#12]
## Issue description

Error running nv-wavenet test for PyTorch

## Code example
```
$ python3.6 nv-wavenet/pytorch/nv_wavenet_test.py
GPUassert: invalid device function ../nv_wavenet_util.cuh 48
```

## System Info
PyTorch version: 0.4.0
Python version: 3.6.4
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/local/lib/python2.7/dist-packages/torch/lib/libcudnn-7a90c013.so.7.0.5
/usr/local/lib/python3.5/dist-packages/torch/lib/libcudnn-3f9a723f.so.6.0.21

**Comment by will-rice** [comment]
I had a similar error the first time I tried the test. I updated to the newest version of CUDA and it fixed it.

**Comment by PetrochukM** [comment]
Ditto --arch parameter, discovered that before I saw your comment.
